Repository projectLevelup/levelup_backend, pull requests merged in 2025-03, with the labels that each got.

#132 feat: Community Comment Api
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/levelup_backend/domain/comment/dto/request/CommentCreateRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/comment/dto/request/CommentUpdateRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/comment/entity/CommentEntity.java
  src/main/java/com/sparta/levelup_backend/domain/comment/repository/CommentRepository.java
  src/main/java/com/sparta/levelup_backend/domain/comment/service/CommentService.java
  src/main/java/com/sparta/levelup_backend/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/community/document/CommunityDocument.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityCommentResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityReadResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityService.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
Labels: 김효중

#134 feat: Community Read Api By Elastic Search
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/community/document/CommunityDocument.java
  src/main/java/com/sparta/levelup_backend/domain/community/repository/CommunityRepository.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityService.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityServiceImpl.java
Labels: 김효중

#136 add : rabbitMQ
  build.gradle
  src/main/java/com/sparta/levelup_backend/common/apiResponse/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/config/StompConfig.java
  src/main/java/com/sparta/levelup_backend/config/listener/BillEventListener.java
  src/main/java/com/sparta/levelup_backend/config/listener/RedisExpireListener.java
  src/main/java/com/sparta/levelup_backend/config/rabbitMQ/RabbitMQConfig.java
  src/main/java/com/sparta/levelup_backend/config/redis/RedisConfig.java
  src/main/java/com/sparta/levelup_backend/domain/bill/dto/PubBillDto.java
  src/main/java/com/sparta/levelup_backend/domain/bill/dto/responseDto/BillCreatedEvent.java
  src/main/java/com/sparta/levelup_backend/domain/bill/dto/responseDto/BillStatusMessageDto.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillEventListener.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillEventPubService.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillEventPublisher.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillServiceImplV2.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillStatusSubscriber.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/NotificationService.java
  src/main/java/com/sparta/levelup_backend/domain/notification/controller/NotificationController.java
  src/main/java/com/sparta/levelup_backend/domain/notification/entity/Notification.java
  src/main/java/com/sparta/levelup_backend/domain/notification/repository/NotificationRepository.java
  src/main/java/com/sparta/levelup_backend/domain/notification/service/NotificationImpl.java
  src/main/java/com/sparta/levelup_backend/domain/notification/service/NotificationService.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/PaymentService.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/PaymentServiceImpl.java
  src/main/java/com/sparta/levelup_backend/enums/NotificationStatus.java
  src/main/java/com/sparta/levelup_backend/enums/NotificationType.java
  src/main/resources/application.yml
  src/main/resources/templates/payment/checkout.html
Labels: 이동건

#137 refactor: rabbitMQ
  src/main/java/com/sparta/levelup_backend/config/database/ElasticsearchConfig.java
  src/main/java/com/sparta/levelup_backend/config/database/JpaConfig.java
  src/main/java/com/sparta/levelup_backend/config/database/MongoDBConfig.java
  src/main/java/com/sparta/levelup_backend/config/database/QuerydslConfig.java
Labels: 이동건

#138 fix: All Detail Control
  build.gradle
  logstash.conf
  src/main/java/com/sparta/levelup_backend/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/sparta/levelup_backend/domain/product/controller/ProductController.java
  src/main/java/com/sparta/levelup_backend/domain/product/entity/ProductEntity.java
  src/main/java/com/sparta/levelup_backend/domain/product/service/ProductServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/product/service/ProductmakedataService.java
  src/main/resources/logback-spring.xml
Labels: 이경훈

#139 feat: Community Api Using Dsl
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityListResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityReadResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/entity/CommunityEntity.java
  src/main/java/com/sparta/levelup_backend/domain/community/repository/CommunityQueryRepository.java
  src/main/java/com/sparta/levelup_backend/domain/community/repository/CommunityRepository.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityService.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/game/entity/GameEntity.java
Labels: 김효중

#141 fix: Delete Useless Api
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/community/document/CommunityDocument.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/repository/CommunityQueryRepository.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityService.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityServiceImpl.java
Labels: 김효중

#144 fix: Remove HTML API Version
  src/main/resources/templates/chatMain.html
  src/main/resources/templates/chatroom.html
  src/main/resources/templates/chatroomList.html
Labels: 최대현

#143 feat: Refactored Community Api
  src/main/java/com/sparta/levelup_backend/common/apiResponse/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/levelup_backend/domain/comment/dto/request/CommentCreateRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/comment/dto/request/CommentUpdateRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/comment/entity/CommentEntity.java
  src/main/java/com/sparta/levelup_backend/domain/comment/repository/CommentRepository.java
  src/main/java/com/sparta/levelup_backend/domain/comment/service/CommentService.java
  src/main/java/com/sparta/levelup_backend/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/community/document/CommunityDocument.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityCommentResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityListResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityReadResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/entity/CommunityEntity.java
  src/main/java/com/sparta/levelup_backend/domain/community/repository/CommunityQueryRepository.java
  src/main/java/com/sparta/levelup_backend/domain/community/repository/CommunityRepository.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityService.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/game/entity/GameEntity.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
Labels: 김효중

#145 fix: Wrong Routes
  src/main/java/com/sparta/levelup_backend/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/levelup_backend/domain/comment/service/CommentServiceImpl.java
Labels: 김효중

#147 recfactor: Review Recfactor
  src/main/java/com/sparta/levelup_backend/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/levelup_backend/domain/review/repository/ReviewQueryRepository.java
  src/main/java/com/sparta/levelup_backend/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/levelup_backend/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/review/ReviewException.java
Labels: 최대현

#156 recfactor: Change All Convention
  logstash.conf
  src/main/java/com/sparta/levelup_backend/domain/product/controller/ProductController.java
  src/main/java/com/sparta/levelup_backend/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/levelup_backend/domain/product/service/ProductServiceImpl.java
  src/main/java/com/sparta/levelup_backend/enums/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/exception/product/ProductException.java
Labels: 이경훈

#158 recfactor: Change All Convention
  src/main/java/com/sparta/levelup_backend/domain/product/controller/ProductController.java
  src/main/java/com/sparta/levelup_backend/domain/product/service/ProductServiceImpl.java
Labels: 이경훈

#159 recfactor: Change All Convention
  src/main/java/com/sparta/levelup_backend/domain/product/controller/ProductController.java
Labels: 이경훈

#160 refactor : Pay refactor
  src/main/java/com/sparta/levelup_backend/domain/bill/controller/BillController.java
  src/main/java/com/sparta/levelup_backend/domain/bill/entity/BillEntity.java
  src/main/java/com/sparta/levelup_backend/domain/bill/repository/BillRepository.java
  src/main/java/com/sparta/levelup_backend/domain/bill/repository/BillRepositoryImpl.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillEventPublisher.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillService.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/notification/entity/Notification.java
  src/main/java/com/sparta/levelup_backend/domain/notification/service/NotificationImpl.java
  src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
  src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderControllerV2.java
  src/main/java/com/sparta/levelup_backend/domain/order/entity/OrderEntity.java
  src/main/java/com/sparta/levelup_backend/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImplV2.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceV2.java
  src/main/java/com/sparta/levelup_backend/domain/payment/controller/PaymentController.java
  src/main/java/com/sparta/levelup_backend/domain/payment/controller/PaymentRestController.java
  src/main/java/com/sparta/levelup_backend/domain/payment/entity/PaymentEntity.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/PaymentRestServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/PaymentServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/bill/BillException.java
  src/main/java/com/sparta/levelup_backend/exception/order/OrderException.java
Labels: 이동건

#161 refactor: Community Convention
  src/main/java/com/sparta/levelup_backend/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/levelup_backend/domain/comment/entity/CommentEntity.java
  src/main/java/com/sparta/levelup_backend/domain/comment/repository/CommentRepository.java
  src/main/java/com/sparta/levelup_backend/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/community/entity/CommunityEntity.java
  src/main/java/com/sparta/levelup_backend/domain/community/repository/CommunityRepository.java
  src/main/java/com/sparta/levelup_backend/domain/community/repositoryes/CommunityESRepository.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/game/controller/GameController.java
  src/main/java/com/sparta/levelup_backend/domain/game/entity/GameEntity.java
  src/main/java/com/sparta/levelup_backend/domain/game/repository/GameRepository.java
  src/main/java/com/sparta/levelup_backend/domain/game/service/GameServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/comment/CommentException.java
  src/main/java/com/sparta/levelup_backend/exception/community/CommunityException.java
  src/main/java/com/sparta/levelup_backend/exception/game/GameException.java
Labels: 김효중

#163 fix : Payment fix
  src/main/java/com/sparta/levelup_backend/domain/payment/controller/PaymentController.java
  src/main/java/com/sparta/levelup_backend/domain/payment/controller/PaymentRestController.java
  src/main/java/com/sparta/levelup_backend/domain/product/service/ProductServiceImpl.java
  src/main/resources/templates/payment/checkout.html
Labels: 이동건

#164 refactor: Chat Recfactor
  src/main/java/com/sparta/levelup_backend/common/apiresponse/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatController.java
  src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatroomController.java
  src/main/java/com/sparta/levelup_backend/domain/chat/document/ChatMessage.java
  src/main/java/com/sparta/levelup_backend/domain/chat/dto/request/ChatRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/chat/dto/response/ChatResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/chat/dto/response/ChatroomCreateResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatMongoRepository.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatroomMongoRepository.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatroomServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/RedisSubscriber.java
  src/main/java/com/sparta/levelup_backend/exception/chat/ChatException.java
  src/main/resources/templates/chatroom.html
Labels: 최대현

#165 fix: Community ApiResMessages
  src/main/java/com/sparta/levelup_backend/common/apiresponse/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/game/controller/GameController.java
Labels: 김효중

#166 test: Test Code Fix
  src/main/java/com/sparta/levelup_backend/domain/chat/dto/response/ChatroomCreateResponseDto.java
  src/test/java/com/sparta/levelup_backend/domain/chat/service/ChatroomServiceImplTest.java
  src/test/java/com/sparta/levelup_backend/domain/review/service/ReviewServiceImplTest.java
Labels: 최대현

#167 fix: IsDeleted Cound Error Clear
  build.gradle
  logstash.conf
  src/main/java/com/sparta/levelup_backend/config/redis/RedisConfig.java
  src/main/java/com/sparta/levelup_backend/domain/product/controller/ProductController.java
  src/main/java/com/sparta/levelup_backend/domain/product/service/ProductServiceImpl.java
  src/main/resources/logback-spring.xml
Labels: 이경훈

#168 add : OrderAdd
  README.md
  src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
  src/main/java/com/sparta/levelup_backend/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderService.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/RateLimitService.java
Labels: 이동건

#170 fix : Order Add
  src/main/java/com/sparta/levelup_backend/config/redis/RedisConfig.java
  src/main/java/com/sparta/levelup_backend/domain/bill/repository/BillRepositoryImpl.java
  src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
  src/main/java/com/sparta/levelup_backend/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderService.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
Labels: 이동건

#172 feat: Image Upload
  build.gradle
  src/main/java/com/sparta/levelup_backend/config/s3/S3Config.java
  src/main/java/com/sparta/levelup_backend/domain/game/controller/GameController.java
  src/main/java/com/sparta/levelup_backend/domain/s3/service/S3Service.java
  src/main/java/com/sparta/levelup_backend/enums/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/exception/s3/S3Exception.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 김효중

#175 refactor: Add Game Image
  src/main/java/com/sparta/levelup_backend/domain/comment/dto/CommentValidMessage.java
  src/main/java/com/sparta/levelup_backend/domain/comment/dto/request/CommentCreateRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/comment/dto/request/CommentUpdateRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/community/repository/CommunityQueryRepository.java
  src/main/java/com/sparta/levelup_backend/domain/game/controller/GameController.java
  src/main/java/com/sparta/levelup_backend/domain/game/dto/GameValidMessage.java
  src/main/java/com/sparta/levelup_backend/domain/game/dto/requestDto/CreateGameRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/game/dto/requestDto/GameCreateRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/game/dto/requestDto/GameUpdateRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/game/dto/requestDto/UpdateGameRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/game/dto/responseDto/GameResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/game/service/GameService.java
  src/main/java/com/sparta/levelup_backend/domain/game/service/GameServiceImpl.java
Labels: 김효중

#177 fix: Top3 Error Clear
  src/main/java/com/sparta/levelup_backend/config/redis/RedisConfig.java
  src/main/java/com/sparta/levelup_backend/domain/product/service/ProductServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/review/document/ReviewDocument.java
  src/main/java/com/sparta/levelup_backend/domain/review/repositoryES/ReviewESRepository.java
Labels: 이경훈

#178 fix: Changing Top3 Not Has ProductId
  src/main/java/com/sparta/levelup_backend/domain/product/dto/request/ProductRequestAllDto.java
Labels: 이경훈
