Repository projectLevelup/levelup_backend, pull requests merged in 2025-02, with the labels that each got.

#1 feat : orderCreate
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
  src/main/java/com/sparta/levelup_backend/domain/order/dto/requestDto/OrderCreateRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/order/dto/responseDto/OrderCreateResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/order/entity/OrderEntity.java
  src/main/java/com/sparta/levelup_backend/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderService.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderSevice.java
  src/main/java/com/sparta/levelup_backend/domain/product/controller/ProductController.java
  src/main/java/com/sparta/levelup_backend/domain/product/entity/ProductEntity.java
  src/main/java/com/sparta/levelup_backend/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/levelup_backend/domain/product/service/ProductService.java
  src/main/java/com/sparta/levelup_backend/domain/product/service/ProductServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/user/entity/UserEntity.java
  src/main/java/com/sparta/levelup_backend/domain/user/userservice/UserService.java
  src/main/java/com/sparta/levelup_backend/domain/user/userservice/UserServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/levelup_backend/exception/common/BusinessException.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/exception/common/NotFoundException.java
  src/main/java/com/sparta/levelup_backend/exception/common/ProductOutOfAmount.java
Labels: 이동건

#4 feat: review create API
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/levelup_backend/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/levelup_backend/domain/review/dto/request/ReviewRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/review/entity/ReviewEntity.java
  src/main/java/com/sparta/levelup_backend/domain/review/service/ReviewService.java
  src/main/java/com/sparta/levelup_backend/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/user/entity/UserEntity.java
  src/test/java/com/sparta/levelup_backend/domain/review/controller/ReviewControllerTest.java
Labels: 최대현

#3 feat : orderRead
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
  src/main/java/com/sparta/levelup_backend/domain/order/dto/OrderValidationMessage.java
  src/main/java/com/sparta/levelup_backend/domain/order/dto/requestDto/OrderCreateRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/order/dto/responseDto/OrderCreateResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/order/dto/responseDto/OrderResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderService.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
Labels: 이동건

#13 fix : Order read
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
  src/main/java/com/sparta/levelup_backend/domain/order/dto/OrderValidationMessage.java
  src/main/java/com/sparta/levelup_backend/domain/order/dto/requestDto/OrderCreateRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/order/dto/responseDto/OrderCreateResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/order/dto/responseDto/OrderResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderService.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/exception/common/ForbiddenException.java
Labels: 이동건

#9 feat : Order update
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
  src/main/java/com/sparta/levelup_backend/domain/order/entity/OrderEntity.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderService.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/user/service/UserService.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/exception/common/ForbiddenException.java
  src/main/java/com/sparta/levelup_backend/exception/common/OrderException.java
Labels: 이동건

#16 fix : oderUser
  src/main/java/com/sparta/levelup_backend/common/entity/BaseEntity.java
  src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
  src/main/java/com/sparta/levelup_backend/domain/order/entity/OrderEntity.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderService.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
Labels: 이동건

#17 feat: Review remove
  build.gradle
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/common/ApiResponse.java
  src/main/java/com/sparta/levelup_backend/common/entity/BaseEntity.java
  src/main/java/com/sparta/levelup_backend/config/CustomUserDetails.java
  src/main/java/com/sparta/levelup_backend/config/CustomUsernamePasswordAuthenticationFilter.java
  src/main/java/com/sparta/levelup_backend/config/JwtFilter.java
  src/main/java/com/sparta/levelup_backend/config/SecurityConfig.java
  src/main/java/com/sparta/levelup_backend/domain/auth/controller/AuthController.java
  src/main/java/com/sparta/levelup_backend/domain/auth/dto/request/SignInUserRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/auth/dto/request/SignUpUserRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/auth/service/AuthService.java
  src/main/java/com/sparta/levelup_backend/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/auth/service/CustomUserDetailsService.java
  src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/levelup_backend/domain/review/entity/ReviewEntity.java
  src/main/java/com/sparta/levelup_backend/domain/review/service/ReviewService.java
  src/main/java/com/sparta/levelup_backend/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/user/entity/UserEntity.java
  src/main/java/com/sparta/levelup_backend/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/levelup_backend/domain/user/service/UserService.java
  src/main/java/com/sparta/levelup_backend/domain/user/service/UserServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/user/userservice/UserService.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/utill/JwtUtils.java
  src/test/java/com/sparta/levelup_backend/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/sparta/levelup_backend/domain/review/service/ReviewServiceImplTest.java
Labels: 최대현

#19 feat : orderComplete
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderService.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
Labels: 이동건

#21 feat : Order delete
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
  src/main/java/com/sparta/levelup_backend/domain/order/entity/OrderEntity.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderService.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
Labels: 이동건

#20 fix: CRUD fix
  src/main/java/com/sparta/levelup_backend/common/entity/BaseEntity.java
  src/main/java/com/sparta/levelup_backend/config/CustomUserDetails.java
  src/main/java/com/sparta/levelup_backend/domain/product/controller/ProductController.java
  src/main/java/com/sparta/levelup_backend/domain/product/dto/requestDto/ProductCreateRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/product/dto/requestDto/ProductRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/product/dto/requestDto/ProductUpdateRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/product/dto/responseDto/ProductCreateResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/product/dto/responseDto/ProductDeleteResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/product/dto/responseDto/ProductResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/product/dto/responseDto/ProductUpdateResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/product/entity/ProductEntity.java
  src/main/java/com/sparta/levelup_backend/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/levelup_backend/domain/product/service/ProductServiceImpl.java
Labels: 이경훈

#22 User read
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/user/controller/UserController.java
  src/main/java/com/sparta/levelup_backend/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/user/service/UserService.java
  src/main/java/com/sparta/levelup_backend/domain/user/service/UserServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ForbiddenException.java
Labels: 정영균

#24 Fix: add token role,id
  src/main/java/com/sparta/levelup_backend/config/CustomUsernamePasswordAuthenticationFilter.java
  src/main/java/com/sparta/levelup_backend/config/JwtFilter.java
  src/main/java/com/sparta/levelup_backend/utill/JwtUtils.java
Labels: 정영균

#27 feat : Review find
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/config/QuerydslConfig.java
  src/main/java/com/sparta/levelup_backend/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/levelup_backend/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/review/entity/ReviewEntity.java
  src/main/java/com/sparta/levelup_backend/domain/review/repository/ReviewQueryRepository.java
  src/main/java/com/sparta/levelup_backend/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/levelup_backend/domain/review/service/ReviewService.java
  src/main/java/com/sparta/levelup_backend/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/exception/common/ForbiddenAccessException.java
  src/main/java/com/sparta/levelup_backend/exception/common/MismatchException.java
  src/test/java/com/sparta/levelup_backend/domain/review/service/ReviewServiceImplTest.java
Labels: 최대현

#23 feat : OrderCRUD
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/common/entity/BaseEntity.java
  src/main/java/com/sparta/levelup_backend/domain/game/repository/GameRepository.java
  src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
  src/main/java/com/sparta/levelup_backend/domain/order/entity/OrderEntity.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderService.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/user/service/UserService.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/exception/common/OrderException.java
Labels: 이동건

#26 feat: Game CRUD
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/common/entity/BaseEntity.java
  src/main/java/com/sparta/levelup_backend/domain/game/controller/GameController.java
  src/main/java/com/sparta/levelup_backend/domain/game/dto/requestDto/CreateGameRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/game/dto/requestDto/FindGameRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/game/dto/requestDto/UpdateGameRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/game/dto/responseDto/GameResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/game/entity/GameEntity.java
  src/main/java/com/sparta/levelup_backend/domain/game/repository/GameRepository.java
  src/main/java/com/sparta/levelup_backend/domain/game/repsitory/GameRepository.java
  src/main/java/com/sparta/levelup_backend/domain/game/service/GameService.java
  src/main/java/com/sparta/levelup_backend/domain/game/service/GameServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/exception/common/ForbiddenException.java
Labels: 김효중

#30 fix: delete comment
  src/main/java/com/sparta/levelup_backend/domain/game/controller/GameController.java
  src/main/java/com/sparta/levelup_backend/domain/game/dto/requestDto/CreateGameRequestDto.java
Labels: 김효중

#31 feat: review refactor
  build.gradle
  src/main/java/com/sparta/levelup_backend/domain/game/repository/GameRepository.java
  src/main/java/com/sparta/levelup_backend/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/levelup_backend/domain/review/entity/ReviewEntity.java
  src/main/java/com/sparta/levelup_backend/domain/review/repository/ReviewQueryRepository.java
  src/main/java/com/sparta/levelup_backend/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/levelup_backend/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/DuplicateException.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/test/java/com/sparta/levelup_backend/domain/review/service/ReviewServiceImplTest.java
Labels: 최대현

#35 merge: game to develop
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/game/controller/GameController.java
  src/main/java/com/sparta/levelup_backend/domain/game/dto/requestDto/CreateGameRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/game/dto/requestDto/FindGameRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/game/dto/requestDto/UpdateGameRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/game/dto/responseDto/GameResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/game/entity/GameEntity.java
  src/main/java/com/sparta/levelup_backend/domain/game/repository/GameRepository.java
  src/main/java/com/sparta/levelup_backend/domain/game/service/GameService.java
  src/main/java/com/sparta/levelup_backend/domain/game/service/GameServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/exception/common/ForbiddenException.java
Labels: 김효중

#33 feat: review curd
  build.gradle
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/config/QuerydslConfig.java
  src/main/java/com/sparta/levelup_backend/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/levelup_backend/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/levelup_backend/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/levelup_backend/domain/review/dto/ReviewValidMessage.java
  src/main/java/com/sparta/levelup_backend/domain/review/dto/request/ReviewRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/review/entity/ReviewEntity.java
  src/main/java/com/sparta/levelup_backend/domain/review/repository/ReviewQueryRepository.java
  src/main/java/com/sparta/levelup_backend/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/levelup_backend/domain/review/service/ReviewService.java
  src/main/java/com/sparta/levelup_backend/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/user/entity/UserEntity.java
  src/main/java/com/sparta/levelup_backend/exception/common/DuplicateException.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/exception/common/ForbiddenAccessException.java
  src/main/java/com/sparta/levelup_backend/exception/common/MismatchException.java
  src/test/java/com/sparta/levelup_backend/domain/review/service/ReviewServiceImplTest.java
Labels: 최대현

#34 fix: Product CRUD Update And Error Clear
  src/main/java/com/sparta/levelup_backend/domain/game/repository/GameRepository.java
  src/main/java/com/sparta/levelup_backend/domain/product/controller/ProductController.java
  src/main/java/com/sparta/levelup_backend/domain/product/dto/ValidMessage.java
  src/main/java/com/sparta/levelup_backend/domain/product/dto/responseDto/ProductDeleteResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/product/service/ProductService.java
  src/main/java/com/sparta/levelup_backend/domain/product/service/ProductServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/product/service/ProductmakedataService.java
Labels: 이경훈

#37 fix: forbiddenAccessException remove
  src/main/java/com/sparta/levelup_backend/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ForbiddenAccessException.java
  src/test/java/com/sparta/levelup_backend/domain/review/service/ReviewServiceImplTest.java
Labels: 최대현

#39 feat: merge user crud
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/config/CustomAccessDeniedHandler.java
  src/main/java/com/sparta/levelup_backend/config/CustomUserDetails.java
  src/main/java/com/sparta/levelup_backend/config/CustomUsernamePasswordAuthenticationFilter.java
  src/main/java/com/sparta/levelup_backend/config/FilterResponse.java
  src/main/java/com/sparta/levelup_backend/config/JwtFilter.java
  src/main/java/com/sparta/levelup_backend/config/SecurityConfig.java
  src/main/java/com/sparta/levelup_backend/domain/auth/controller/AuthController.java
  src/main/java/com/sparta/levelup_backend/domain/auth/dto/request/SignUpUserRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/auth/service/CustomUserDetailsService.java
  src/main/java/com/sparta/levelup_backend/domain/game/repository/GameRepository.java
  src/main/java/com/sparta/levelup_backend/domain/user/controller/UserController.java
  src/main/java/com/sparta/levelup_backend/domain/user/dto/request/ChangePasswordDto.java
  src/main/java/com/sparta/levelup_backend/domain/user/dto/request/DeleteUserRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/user/dto/request/UpdateUserImgUrlReqeustDto.java
  src/main/java/com/sparta/levelup_backend/domain/user/dto/request/UpdateUserRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/user/entity/UserEntity.java
  src/main/java/com/sparta/levelup_backend/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/levelup_backend/domain/user/service/UserService.java
  src/main/java/com/sparta/levelup_backend/domain/user/service/UserServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/AlreadyDeletedUserException.java
  src/main/java/com/sparta/levelup_backend/exception/common/CurrentPasswordNotMatchedException.java
  src/main/java/com/sparta/levelup_backend/exception/common/EmailDuplicatedException.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/exception/common/PasswordConfirmNotMatchedException.java
  src/main/java/com/sparta/levelup_backend/utill/JwtUtils.java
  src/main/java/com/sparta/levelup_backend/utill/UserRole.java
Labels: 정영균

#40 add : ApiResponseAdive
  src/main/java/com/sparta/levelup_backend/common/ApiResponseAdvice.java
Labels: 이동건

#41 fix : orderRefactor
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
Labels: 이동건

#44 feat: OrderFix
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
Labels: 이동건

#45 Fix : OrderFix
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
Labels: 이동건

#46 fix: valid and forbidden enum
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/config/CustomAccessDeniedHandler.java
  src/main/java/com/sparta/levelup_backend/domain/auth/dto/request/SignUpUserRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/user/dto/UserValidMessage.java
  src/main/java/com/sparta/levelup_backend/domain/user/dto/request/ChangePasswordDto.java
  src/main/java/com/sparta/levelup_backend/domain/user/dto/request/DeleteUserRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/user/dto/request/UpdateUserRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/user/service/UserServiceImpl.java
Labels: 정영균

#49 Fix : OrderFix
  src/main/java/com/sparta/levelup_backend/domain/order/dto/responseDto/OrderResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
Labels: 이동건

#51 fix: reviews find nickname / productId remove
  src/main/java/com/sparta/levelup_backend/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/review/repository/ReviewQueryRepository.java
Labels: 최대현

#53 fix: add header token
  src/main/java/com/sparta/levelup_backend/config/CustomAccessDeniedHandler.java
  src/main/java/com/sparta/levelup_backend/config/CustomUsernamePasswordAuthenticationFilter.java
  src/main/java/com/sparta/levelup_backend/config/FilterResponse.java
  src/main/java/com/sparta/levelup_backend/config/JwtFilter.java
Labels: 정영균

#56 fix: Game while merge to develop
  src/main/java/com/sparta/levelup_backend/domain/game/controller/GameController.java
  src/main/java/com/sparta/levelup_backend/domain/game/dto/responseDto/GameListResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/game/service/GameService.java
  src/main/java/com/sparta/levelup_backend/domain/game/service/GameServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
Labels: 김효중

#57 fix: game merge
  src/main/java/com/sparta/levelup_backend/domain/game/controller/GameController.java
  src/main/java/com/sparta/levelup_backend/domain/game/dto/responseDto/GameListResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/game/service/GameService.java
  src/main/java/com/sparta/levelup_backend/domain/game/service/GameServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
Labels: 김효중

#58 fix: response body code convention fix
  src/main/java/com/sparta/levelup_backend/config/CustomUsernamePasswordAuthenticationFilter.java
  src/main/java/com/sparta/levelup_backend/config/FilterResponse.java
Labels: 정영균

#61 fix: response body code convention fix
  src/main/java/com/sparta/levelup_backend/config/CustomUsernamePasswordAuthenticationFilter.java
  src/main/java/com/sparta/levelup_backend/config/FilterResponse.java
Labels: 정영균

#60 fix: Change Dto Response Name
  src/main/java/com/sparta/levelup_backend/domain/game/dto/responseDto/GameListResponseDto.java
Labels: 김효중

#64 fix: Change Dto Response Name
  src/main/java/com/sparta/levelup_backend/domain/game/dto/responseDto/GameListResponseDto.java
Labels: 김효중

#66 feat: chat create
  build.gradle
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/config/CustomUserDetails.java
  src/main/java/com/sparta/levelup_backend/config/StompConfig.java
  src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatController.java
  src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatroomController.java
  src/main/java/com/sparta/levelup_backend/domain/chat/dto/ChatMessageDto.java
  src/main/java/com/sparta/levelup_backend/domain/chat/dto/ChatroomResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/chat/entity/ChatroomEntity.java
  src/main/java/com/sparta/levelup_backend/domain/chat/entity/ChatroomParticipantEntity.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatroomParticipantRepository.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatroomQueryRepository.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatroomRepository.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatroomService.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatroomServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
Labels: 최대현

#68 faet : order bill read
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/config/CustomUserDetails.java
  src/main/java/com/sparta/levelup_backend/domain/bill/controller/BillControllerV2.java
  src/main/java/com/sparta/levelup_backend/domain/bill/dto/responseDto/BillResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/bill/entity/BillEntity.java
  src/main/java/com/sparta/levelup_backend/domain/bill/repository/BillRepository.java
  src/main/java/com/sparta/levelup_backend/domain/bill/repository/BillRepositoryCustom.java
  src/main/java/com/sparta/levelup_backend/domain/bill/repository/BillRepositoryImpl.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillService.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillServiceImplV2.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillServiceV2.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImplV2.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/test/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImplTest.java
Labels: 이동건

#69 feat : orderBillDelete
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/bill/controller/BillControllerV2.java
  src/main/java/com/sparta/levelup_backend/domain/bill/entity/BillEntity.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillServiceImplV2.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillServiceV2.java
Labels: 이동건

#70 feat: chat refactor
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/config/SecurityConfig.java
  src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatroomController.java
  src/main/java/com/sparta/levelup_backend/domain/chat/dto/ChatroomListResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatroomParticipantRepository.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatroomRepository.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatroomService.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatroomServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/proto/JwtAuthenticationSuccessHandler.java
  src/main/java/com/sparta/levelup_backend/proto/TempJwtFilter.java
  src/main/java/com/sparta/levelup_backend/proto/TempJwtUtils.java
  src/main/java/com/sparta/levelup_backend/proto/TempSecurityConfig.java
  src/main/java/com/sparta/levelup_backend/ui/PageController.java
  src/main/resources/static/css/common.css
  src/main/resources/static/img/levelup-logo.png
  src/main/resources/templates/chatroom.html
  src/main/resources/templates/chatroomList.html
  src/main/resources/templates/main.html
  src/main/resources/templates/signup.html
Labels: 최대현

#71 feat : orderBillCancle
  src/main/java/com/sparta/levelup_backend/domain/bill/entity/BillEntity.java
  src/main/java/com/sparta/levelup_backend/domain/bill/repository/BillRepository.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImplV2.java
Labels: 이동건

#76 feat: Save Community Api
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/CommunityValidMessage.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/request/CommnunityCreateRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/entity/CommunityEntity.java
  src/main/java/com/sparta/levelup_backend/domain/community/repository/CommunityRepository.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityService.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityServiceImpl.java
Labels: 김효중

#75 Feat: Access Token and Refresh Token
  build.gradle
  src/main/java/com/sparta/levelup_backend/config/CustomAccessDeniedHandler.java
  src/main/java/com/sparta/levelup_backend/config/CustomUsernamePasswordAuthenticationFilter.java
  src/main/java/com/sparta/levelup_backend/config/FilterResponse.java
  src/main/java/com/sparta/levelup_backend/config/FormToJsonHttpMessageConverter.java
  src/main/java/com/sparta/levelup_backend/config/HttpMessageConverterConfigurer.java
  src/main/java/com/sparta/levelup_backend/config/JwtFilter.java
  src/main/java/com/sparta/levelup_backend/config/SecurityConfig.java
  src/main/java/com/sparta/levelup_backend/config/annotaion/FormToJson.java
  src/main/java/com/sparta/levelup_backend/domain/auth/controller/AuthController.java
  src/main/java/com/sparta/levelup_backend/domain/auth/controller/AuthFormController.java
  src/main/java/com/sparta/levelup_backend/domain/auth/dto/request/SignUpUserRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/auth/service/CustomUserDetailsService.java
  src/main/java/com/sparta/levelup_backend/domain/user/controller/UserController.java
  src/main/java/com/sparta/levelup_backend/domain/user/entity/UserEntity.java
  src/main/java/com/sparta/levelup_backend/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/levelup_backend/domain/user/service/UserServiceImpl.java
  src/main/java/com/sparta/levelup_backend/utill/JwtUtils.java
  src/main/resources/templates/signin.html
  src/main/resources/templates/signup.html
Labels: 정영균

#78 feat: Read Community List Api
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityListResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityReadResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/repository/CommunityRepository.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityService.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/exception/common/PageOutOfBoundsException.java
Labels: 김효중

#77 feat: chat refactor
  build.gradle
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/config/MongoDBConfig.java
  src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatController.java
  src/main/java/com/sparta/levelup_backend/domain/chat/dto/ChatMessageDto.java
  src/main/java/com/sparta/levelup_backend/domain/chat/entity/ChatMessage.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatMongoRepository.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatService.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/sparta/levelup_backend/ui/PageController.java
  src/main/resources/static/css/common.css
  src/main/resources/templates/chatroom.html
  src/main/resources/templates/login.html
Labels: 최대현

#79 feat: Update Community Api
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/CommunityValidMessage.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/request/CommunityUpdateRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/entity/CommunityEntity.java
  src/main/java/com/sparta/levelup_backend/domain/community/repository/CommunityRepository.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityService.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
Labels: 김효중

#80 recfactor: chat refactor
  build.gradle
  src/main/java/com/sparta/levelup_backend/config/RedisChatConfig.java
  src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatController.java
  src/main/java/com/sparta/levelup_backend/domain/chat/dto/ChatMessageDto.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/RedisPublisher.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/RedisSubscriber.java
  src/main/resources/static/css/common.css
  src/main/resources/templates/chatroom.html
Labels: 최대현

#81 feat: Delete Community Api
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/community/entity/CommunityEntity.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityService.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityServiceImpl.java
Labels: 김효중

#84 recfactor: chatroom MySQL -> MongoDB
  src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatController.java
  src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatroomController.java
  src/main/java/com/sparta/levelup_backend/domain/chat/document/ChatMessage.java
  src/main/java/com/sparta/levelup_backend/domain/chat/document/ChatroomDocument.java
  src/main/java/com/sparta/levelup_backend/domain/chat/document/Participant.java
  src/main/java/com/sparta/levelup_backend/domain/chat/dto/ChatroomCreateResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/chat/dto/ChatroomListResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatMongoRepository.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatroomMongoRepository.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatroomQueryRepository.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatroomService.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatroomServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/BadRequestException.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/proto/JwtAuthenticationSuccessHandler.java
Labels: 최대현

#85 feat: Chatrooms UnreadMessages/LastMessage Update
  src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatController.java
  src/main/java/com/sparta/levelup_backend/domain/chat/document/ChatMessage.java
  src/main/java/com/sparta/levelup_backend/domain/chat/dto/ChatMessageDto.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatMongoRepository.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatroomMongoRepository.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatService.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatroomService.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatroomServiceImpl.java
  src/main/java/com/sparta/levelup_backend/ui/PageController.java
  src/main/resources/templates/chatroomList.html
  src/main/resources/templates/productDetail.html
Labels: 최대현

#86 fix: Chat Fix & Test
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/config/SecurityConfig.java
  src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatController.java
  src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatroomController.java
  src/main/java/com/sparta/levelup_backend/domain/chat/dto/ChatroomResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/chat/entity/ChatroomEntity.java
  src/main/java/com/sparta/levelup_backend/domain/chat/entity/ChatroomParticipantEntity.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatroomParticipantRepository.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatroomQueryRepository.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatroomRepository.java
  src/main/java/com/sparta/levelup_backend/proto/JwtAuthenticationSuccessHandler.java
  src/main/java/com/sparta/levelup_backend/proto/TempJwtFilter.java
  src/main/java/com/sparta/levelup_backend/proto/TempJwtUtils.java
  src/main/java/com/sparta/levelup_backend/proto/TempSecurityConfig.java
  src/test/java/com/sparta/levelup_backend/domain/chat/service/ChatroomServiceImplTest.java
Labels: 최대현

#87 feat: Create, Read Community From ElasticSearch Api
  build.gradle
  src/main/java/com/sparta/levelup_backend/config/ElasticsearchConfig.java
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/community/document/CommunityDocument.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityReadResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/repositoryES/CommunityESRepository.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityService.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityServiceImpl.java
Labels: 김효중

#92 fix: Delete Token
  src/main/resources/templates/signin.html
Labels: 정영균

#93 feat: Community ES Update Api
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/community/document/CommunityDocument.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/repositoryES/CommunityESRepository.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityService.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityServiceImpl.java
Labels: 김효중

#91 feat: Chat & Chatroom
  build.gradle
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/config/CustomUserDetails.java
  src/main/java/com/sparta/levelup_backend/config/MongoDBConfig.java
  src/main/java/com/sparta/levelup_backend/config/RedisChatConfig.java
  src/main/java/com/sparta/levelup_backend/config/StompConfig.java
  src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatController.java
  src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatroomController.java
  src/main/java/com/sparta/levelup_backend/domain/chat/document/ChatMessage.java
  src/main/java/com/sparta/levelup_backend/domain/chat/document/ChatroomDocument.java
  src/main/java/com/sparta/levelup_backend/domain/chat/document/Participant.java
  src/main/java/com/sparta/levelup_backend/domain/chat/dto/ChatMessageDto.java
  src/main/java/com/sparta/levelup_backend/domain/chat/dto/ChatroomCreateResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/chat/dto/ChatroomListResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatMongoRepository.java
  src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatroomMongoRepository.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatService.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatroomService.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatroomServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/RedisPublisher.java
  src/main/java/com/sparta/levelup_backend/domain/chat/service/RedisSubscriber.java
  src/main/java/com/sparta/levelup_backend/exception/common/BadRequestException.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/ui/PageController.java
  src/main/resources/static/css/common.css
  src/main/resources/static/img/default-img.png
  src/main/resources/static/img/levelup-logo.png
  src/main/resources/templates/admin.html
  src/main/resources/templates/chatMain.html
  src/main/resources/templates/chatroom.html
  src/main/resources/templates/chatroomList.html
  src/main/resources/templates/checkout.html
  src/main/resources/templates/fragments.html
  src/main/resources/templates/layout.html
  src/main/resources/templates/login.html
  src/main/resources/templates/main.html
  src/main/resources/templates/productCreate.html
  src/main/resources/templates/productDetail.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/signup-temp.html
  src/test/java/com/sparta/levelup_backend/domain/chat/service/ChatroomServiceImplTest.java
Labels: 최대현

#98 feat: Community
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/config/ElasticsearchConfig.java
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/community/document/CommunityDocument.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/CommunityValidMessage.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/request/CommnunityCreateRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/request/CommunityUpdateRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityListResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityReadResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/entity/CommunityEntity.java
  src/main/java/com/sparta/levelup_backend/domain/community/repository/CommunityRepository.java
  src/main/java/com/sparta/levelup_backend/domain/community/repositoryES/CommunityESRepository.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityService.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/exception/common/PageOutOfBoundsException.java
Labels: 김효중

#100 Fix: social login token
  src/main/java/com/sparta/levelup_backend/config/CustomOAuth2Handler.java
  src/main/java/com/sparta/levelup_backend/config/CustomUsernamePasswordAuthenticationFilter.java
  src/main/java/com/sparta/levelup_backend/config/JwtFilter.java
  src/main/java/com/sparta/levelup_backend/config/SecurityConfig.java
  src/main/java/com/sparta/levelup_backend/domain/auth/controller/AuthController.java
  src/main/java/com/sparta/levelup_backend/domain/auth/controller/AuthFormController.java
  src/main/java/com/sparta/levelup_backend/domain/auth/service/AuthService.java
  src/main/java/com/sparta/levelup_backend/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/sparta/levelup_backend/ui/PageController.java
  src/main/resources/templates/main.html
  src/main/resources/templates/signin.html
Labels: 정영균

#101 feat: Payments Toss
  build.gradle
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/common/entity/BaseEntity.java
  src/main/java/com/sparta/levelup_backend/config/JwtFilter.java
  src/main/java/com/sparta/levelup_backend/config/MvcConfiguration.java
  src/main/java/com/sparta/levelup_backend/config/TossPaymentConfig.java
  src/main/java/com/sparta/levelup_backend/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/bill/controller/BillControllerV2.java
  src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderControllerV2.java
  src/main/java/com/sparta/levelup_backend/domain/order/entity/OrderEntity.java
  src/main/java/com/sparta/levelup_backend/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImplV2.java
  src/main/java/com/sparta/levelup_backend/domain/payment/controller/PaymentController.java
  src/main/java/com/sparta/levelup_backend/domain/payment/controller/PaymentRestController.java
  src/main/java/com/sparta/levelup_backend/domain/payment/dto/PaymentValidationMessage.java
  src/main/java/com/sparta/levelup_backend/domain/payment/dto/response/PaymentResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/payment/entity/PaymentEntity.java
  src/main/java/com/sparta/levelup_backend/domain/payment/repository/PaymentRepository.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/PaymentService.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/PaymentServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/levelup_backend/domain/user/controller/UserController.java
  src/main/java/com/sparta/levelup_backend/domain/user/entity/UserEntity.java
  src/main/java/com/sparta/levelup_backend/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/exception/common/PaymentException.java
  src/main/java/com/sparta/levelup_backend/utill/PayType.java
  src/main/resources/templates/fail.html
  src/main/resources/templates/payment/checkout.html
  src/main/resources/templates/payment/success.html
Labels: 이동건

#103 refactor: Payment Toss
  src/main/java/com/sparta/levelup_backend/domain/bill/controller/BillControllerV2.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillServiceImplV2.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImplV2.java
  src/main/java/com/sparta/levelup_backend/domain/payment/PaymentController.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/PaymentServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/resources/templates/payment/checkout.html
Labels: 이동건

#104 add: PaymentsToss
  build.gradle
  src/main/java/com/sparta/levelup_backend/domain/payment/controller/PaymentController.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/PaymentServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/test/java/com/sparta/levelup_backend/domain/payment/controller/PaymentControllerTest.java
Labels: 이동건

#105 feat : Payments cancel
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/bill/entity/BillEntity.java
  src/main/java/com/sparta/levelup_backend/domain/bill/repository/BillRepository.java
  src/main/java/com/sparta/levelup_backend/domain/payment/controller/PaymentController.java
  src/main/java/com/sparta/levelup_backend/domain/payment/controller/PaymentRestController.java
  src/main/java/com/sparta/levelup_backend/domain/payment/dto/PaymentValidationMessage.java
  src/main/java/com/sparta/levelup_backend/domain/payment/dto/request/CancelPaymentRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/payment/dto/response/CancelResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/payment/dto/response/PaymentResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/payment/repository/PaymentRepository.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/PaymentService.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/PaymentServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/RateLimitService.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
Labels: 이동건

#107 feat: Community Creat, Read Api (Redis)
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityReadResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityService.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityServiceImpl.java
Labels: 김효중

#108 add : Redis listener
  src/main/java/com/sparta/levelup_backend/config/RedisConfig.java
  src/main/java/com/sparta/levelup_backend/config/RedisConfigChecker.java
  src/main/java/com/sparta/levelup_backend/config/RedisExpireListener.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImplV2.java
  src/main/java/com/sparta/levelup_backend/domain/payment/controller/PaymentController.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/PaymentServiceImpl.java
  src/test/java/com/sparta/levelup_backend/domain/payment/controller/PaymentControllerTest.java
Labels: 이동건

#110 fix : PaymentsFix
  src/main/java/com/sparta/levelup_backend/config/RedisExpireListener.java
  src/main/java/com/sparta/levelup_backend/domain/payment/controller/PaymentController.java
  src/main/java/com/sparta/levelup_backend/domain/product/service/ProductServiceImpl.java
Labels: 이동건

#111 feat : Payments
  build.gradle
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/common/entity/BaseEntity.java
  src/main/java/com/sparta/levelup_backend/config/CustomUserDetails.java
  src/main/java/com/sparta/levelup_backend/config/JwtFilter.java
  src/main/java/com/sparta/levelup_backend/config/MvcConfiguration.java
  src/main/java/com/sparta/levelup_backend/config/RedisConfig.java
  src/main/java/com/sparta/levelup_backend/config/RedisConfigChecker.java
  src/main/java/com/sparta/levelup_backend/config/RedisExpireListener.java
  src/main/java/com/sparta/levelup_backend/config/TossPaymentConfig.java
  src/main/java/com/sparta/levelup_backend/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/bill/controller/BillControllerV2.java
  src/main/java/com/sparta/levelup_backend/domain/bill/entity/BillEntity.java
  src/main/java/com/sparta/levelup_backend/domain/bill/repository/BillRepository.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillServiceImplV2.java
  src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderControllerV2.java
  src/main/java/com/sparta/levelup_backend/domain/order/entity/OrderEntity.java
  src/main/java/com/sparta/levelup_backend/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImplV2.java
  src/main/java/com/sparta/levelup_backend/domain/payment/controller/PaymentController.java
  src/main/java/com/sparta/levelup_backend/domain/payment/controller/PaymentRestController.java
  src/main/java/com/sparta/levelup_backend/domain/payment/dto/request/CancelPaymentRequestDto.java
  src/main/java/com/sparta/levelup_backend/domain/payment/dto/response/CancelResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/payment/dto/response/PaymentResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/payment/entity/PaymentEntity.java
  src/main/java/com/sparta/levelup_backend/domain/payment/repository/PaymentRepository.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/PaymentService.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/PaymentServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/RateLimitService.java
  src/main/java/com/sparta/levelup_backend/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/levelup_backend/domain/product/service/ProductServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/user/controller/UserController.java
  src/main/java/com/sparta/levelup_backend/domain/user/entity/UserEntity.java
  src/main/java/com/sparta/levelup_backend/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/exception/common/PaymentException.java
  src/main/java/com/sparta/levelup_backend/utill/PayType.java
  src/main/resources/static/style.css
  src/main/resources/templates/fail.html
  src/main/resources/templates/payment/checkout.html
  src/main/resources/templates/payment/success.html
  src/test/java/com/sparta/levelup_backend/LevelupBackendApplicationTests.java
  src/test/java/com/sparta/levelup_backend/domain/payment/controller/PaymentControllerTest.java
Labels: 이동건

#113 feat : RedisMessage
  build.gradle
  src/main/java/com/sparta/levelup_backend/config/BillEventListener.java
  src/main/java/com/sparta/levelup_backend/config/RedisConfig.java
  src/main/java/com/sparta/levelup_backend/domain/bill/dto/responseDto/BillCreatedEvent.java
  src/main/java/com/sparta/levelup_backend/domain/bill/dto/responseDto/BillStatusMessageDto.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillEventPubService.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillServiceImplV2.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillStatusSubscriber.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/NotificationService.java
  src/main/java/com/sparta/levelup_backend/domain/payment/controller/PaymentController.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/PaymentServiceImpl.java
  src/main/java/com/sparta/levelup_backend/utill/BillStatus.java
Labels: 이동건

#115 feat: Community Update, Delete Api
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityService.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityServiceImpl.java
Labels: 김효중

#116 feat : Payments
  build.gradle
  src/main/java/com/sparta/levelup_backend/config/BillEventListener.java
  src/main/java/com/sparta/levelup_backend/config/RedisConfig.java
  src/main/java/com/sparta/levelup_backend/domain/bill/dto/responseDto/BillCreatedEvent.java
  src/main/java/com/sparta/levelup_backend/domain/bill/dto/responseDto/BillStatusMessageDto.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillEventPubService.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillServiceImplV2.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/BillStatusSubscriber.java
  src/main/java/com/sparta/levelup_backend/domain/bill/service/NotificationService.java
  src/main/java/com/sparta/levelup_backend/domain/payment/controller/PaymentController.java
  src/main/java/com/sparta/levelup_backend/domain/payment/service/PaymentServiceImpl.java
  src/main/java/com/sparta/levelup_backend/utill/BillStatus.java
Labels: 이동건

#117 fix: Delete Test Api
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
Labels: 김효중

#120 feat: Community Redis Api
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityReadResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityService.java
  src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityServiceImpl.java
Labels: 김효중

#119 Feat: merge user to dev
  build.gradle
  src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
  src/main/java/com/sparta/levelup_backend/config/AsyncConfig.java
  src/main/java/com/sparta/levelup_backend/config/CustomUserDetails.java
  src/main/java/com/sparta/levelup_backend/config/CustomUsernamePasswordAuthenticationFilter.java
  src/main/java/com/sparta/levelup_backend/config/JwtFilter.java
  src/main/java/com/sparta/levelup_backend/config/SecurityConfig.java
  src/main/java/com/sparta/levelup_backend/domain/alert/controller/AlertController.java
  src/main/java/com/sparta/levelup_backend/domain/alert/dto/AlertMessage.java
  src/main/java/com/sparta/levelup_backend/domain/alert/dto/request/AlertMessageDto.java
  src/main/java/com/sparta/levelup_backend/domain/alert/dto/response/AlertLogResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/alert/entity/AlertMessageEntity.java
  src/main/java/com/sparta/levelup_backend/domain/alert/entity/AlertMessageLogEntity.java
  src/main/java/com/sparta/levelup_backend/domain/alert/event/AlertEvent.java
  src/main/java/com/sparta/levelup_backend/domain/alert/event/AlertEventListener.java
  src/main/java/com/sparta/levelup_backend/domain/alert/event/AlertEventPublisher.java
  src/main/java/com/sparta/levelup_backend/domain/alert/repository/AlertMessageLogRepository.java
  src/main/java/com/sparta/levelup_backend/domain/alert/repository/AlertMessageRepository.java
  src/main/java/com/sparta/levelup_backend/domain/alert/repository/AlertRepository.java
  src/main/java/com/sparta/levelup_backend/domain/alert/service/AlertService.java
  src/main/java/com/sparta/levelup_backend/domain/alert/service/AlertServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/auth/dto/response/GoogleResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/auth/dto/response/KakaoResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/auth/dto/response/NaverResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/auth/dto/response/OAuth2ResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/sparta/levelup_backend/domain/email/dto/request/SendEmailDto.java
  src/main/java/com/sparta/levelup_backend/domain/email/event/EmailEvent.java
  src/main/java/com/sparta/levelup_backend/domain/email/event/EmailEventListener.java
  src/main/java/com/sparta/levelup_backend/domain/email/event/EmailEventPublisher.java
  src/main/java/com/sparta/levelup_backend/domain/email/service/EmailService.java
  src/main/java/com/sparta/levelup_backend/domain/email/service/EmailServiceImpl.java
  src/main/java/com/sparta/levelup_backend/domain/user/controller/UserController.java
  src/main/java/com/sparta/levelup_backend/domain/user/dto/UserMessage.java
  src/main/java/com/sparta/levelup_backend/domain/user/dto/request/ResetPasswordConfirmDto.java
  src/main/java/com/sparta/levelup_backend/domain/user/dto/request/ResetPasswordDto.java
  src/main/java/com/sparta/levelup_backend/domain/user/service/UserService.java
  src/main/java/com/sparta/levelup_backend/domain/user/service/UserServiceImpl.java
  src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
  src/main/java/com/sparta/levelup_backend/ui/PageController.java
  src/main/resources/templates/resetPassword.html
  src/main/resources/templates/resetPasswordConfirm.html
  src/main/resources/templates/signin.html
Labels: 정영균

#122 Feat: Replace Cookie Url Location
  src/main/java/com/sparta/levelup_backend/config/CustomOAuth2Handler.java
  src/main/java/com/sparta/levelup_backend/config/JwtFilter.java
  src/main/java/com/sparta/levelup_backend/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/sparta/levelup_backend/utill/JwtUtils.java
  src/main/resources/templates/signin.html
Labels: 정영균

#124 Fix: remove cookie domain
  src/main/java/com/sparta/levelup_backend/config/CustomOAuth2Handler.java
  src/main/java/com/sparta/levelup_backend/config/JwtFilter.java
  src/main/java/com/sparta/levelup_backend/domain/alert/dto/response/AlertLogResponseDto.java
  src/main/java/com/sparta/levelup_backend/domain/auth/service/AuthServiceImpl.java
Labels: 정영균

#127 feat: Develop CICD
  .gitignore
  Dockerfile
  mongo-init.js
  redis.conf
  src/main/java/com/sparta/levelup_backend/config/ElasticsearchConfig.java
  src/main/java/com/sparta/levelup_backend/config/RedisConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 최대현
